import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Plus, Github } from "lucide-react";
import { SearchBox } from "@/components/SearchBox";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ponies.fyi",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex lg:w-2/3 m-auto border-b border-gray-400/50">
          <div className="flex flex-1 items-center gap-1">
            <img className="object-fit w-[64px] -m-4" src="/derpy.png" />
            <Link href="/" className="font-equestria ml-4">ponies.fyi</Link>
            <p className="self-end mb-2">An open-source index for discovering and referencing ponysonas</p>
          </div>
          <SearchBox />
          <div className="flex items-center gap-4 mr-4">
            <a href="/pages/create" title="Add pony" className="cursor-pointer">
              <Plus />
            </a>
            <a
              href="https://github.com/compscitwilight/ponies.fyi"
              target="_blank"
              title="Source code"
              className="flex items-center gap-1 cursor-pointer transition-text duration-200 hover:text-blue-500"
            >
              <Github />
              <p>version b1.0</p>
            </a>
          </div>
        </div>
        {/* <div className="text-center w-full border border-yellow-300 bg-yellow-200/75 py-1 my-2 font-bold">
          <p>Testing this for development</p>
        </div> */}
        <div className="lg:w-1/2 m-auto mt-8">
          {children}
        </div>
      </body>
    </html>
  );
}
